title: Twin Cities Real Estate Video Blog with Nicole Junker
description: Our mission at -- client brand -- is to be your best resource for -- market -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- client brand --, your professional -- market -- Real Estate Agents.
show_custom_links: show
custom_links:
  - title: Schedule a Meeting with Nicole
    url: https://calendly.com/nicolejunker/60min
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Nicole Junker
  title:
  license_number:
  about_markdown: |
    Nicole is known among her contemporaries as a consummate professional. Starting in the real estate industry in 2000, Nicole's expertise began in mortgage and financing, closing more than $100 million in mortgage transactions over 8 years. In 2008, Nicole became a real estate agent, where she is able to be empathetic and yet savvy to the needs of both buyers and sellers. Her experience in the mortgage industry directly translates to helping hundreds of families navigate the home-buying and home-selling process while achieving their goals of finding their dream home.

    As one of the Pemberton Homes Teams senior agents, Nicole offers a diverse selection of services. As an owner of investment property, she can assist investors in finding the right property for their business. Nicole is also a trained Senior Real Estate Specialist (SRES®) that can assist mature clients in downsizing out of their single-family homes.

    Nicole's services span the Twin Cities, focusing on the south metro. Nicole has been honored to be named the Reader's Choice: Best Realtor in Apple Valley, MN (Sun Current Newspaper) for 4 years in a row, 2017-2020.
  brand:
  brokerage: exp Realty
  market: Twin Cities
  address:
  phone: 651-373-1211
  phone_type:
  phone2:
  phone2_type:
  email: nicole@teampemberton.com
  url: https://nicolejunker.exprealty.com

forms:
  sitekey:

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://nicolejunker.exprealty.com/seller/valuation/
  second_CTA_text: Home Search
  second_CTA_URL: https://nicolejunker.exprealty.com/index.php?showagent=1&rtype=map

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://nicolejunker.exprealty.com/seller/valuation/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Home?"
    CTA_text2: "Search the entire MLS for your home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://nicolejunker.exprealty.com/index.php?showagent=1&rtype=map

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
  google_business_url:

podcast:
  title: '-- market -- Real Estate Podcast with -- client name --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- market -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- client brand -- - your professional -- market -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- market --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- client name --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Twin Cities Real Estate Video Blog   
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg
  header_overlay: rgba(0, 0, 0, 0.1)

site_colors:
  brand_color: '#0c7f86'
  theme_color: '#000000'
  theme_text_color: '#1d2959'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: white

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
